name: Test And Linter

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
    - uses: FedericoCarboni/setup-ffmpeg@v1
      with:
        go-version: 1.15
    id: setup-ffmpeg

    - name: Run Test
      run: go mod tidy && go test ./...