name: Test And Linter

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: FedericoCarboni/setup-ffmpeg@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: setup-ffmpeg

    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
      env:
          API_KEY: ${{ secrets.API_KEY }}
    - name: Run Test
      run: go mod tidy && go test ./...

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}